2023-02-05 08:34:14,046 : kivy : Factory: 189 symbols loaded
2023-02-05 08:34:14,171 : kivy : ImageLoaderFFPy: Using ffpyplayer 4.3.5
2023-02-05 08:34:14,171 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
2023-02-05 08:34:14,206 : kivy : VideoGstplayer: Using Gstreamer 1.18.5.0
2023-02-05 08:34:14,207 : kivy : Video: Provider: gstplayer
2023-02-05 08:34:14,398 : kivy : Loading MPF-MC controller
2023-02-05 08:34:14,400 : YamlMultifileConfigLoader : Machine config file #1: config
2023-02-05 08:34:14,400 : ConfigProcessor : Config file in cache changed: C:\pinball\SAW\config\config
2023-02-05 08:34:14,402 : ConfigProcessor : Loading config from file C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\mcconfig.yaml.
2023-02-05 08:34:14,427 : ConfigProcessor : Loading config: C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\mcconfig.yaml
2023-02-05 08:34:14,427 : ConfigProcessor : Loading config from file C:\pinball\SAW\config\config.
2023-02-05 08:34:14,453 : ConfigProcessor : Loading config: C:\pinball\SAW\config\config
2023-02-05 08:34:14,454 : ConfigProcessor : Config file cache created: C:\Users\steel\AppData\Local\Temp\785655ce0a6ad62be8f20f2598aadce2.mpf_cache
2023-02-05 08:34:14,454 : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\0c159a05f39617a30cc1b279562f144f.mpf_cache
2023-02-05 08:34:14,455 : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\a4144dd661fe0832b800e50000db3090.mpf_cache
2023-02-05 08:34:14,456 : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\0c159a05f39617a30cc1b279562f144f.mpf_cache
2023-02-05 08:34:14,456 : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\c84db42795c08bfb8e4272b3be41e3f4.mpf_cache
2023-02-05 08:34:14,460 : mpfmc : Mission Pinball Framework Media Controller v0.56.0-dev33
2023-02-05 08:34:14,460 : mpfmc : Mission Pinball Framework Game Engine v0.56.0-dev33
2023-02-05 08:34:14,460 : mpfmc : Machine path: C:\pinball\SAW
2023-02-05 08:34:14,460 : mpfmc : Starting clock at 60.0Hz
2023-02-05 08:34:14,473 : kivy : Text: Provider: sdl2
2023-02-05 08:34:14,510 : kivy : Window: Provider: sdl2
2023-02-05 08:34:14,745 : kivy : GL: Using the "OpenGL" graphics system
2023-02-05 08:34:14,746 : kivy : GL: GLEW initialization succeeded
2023-02-05 08:34:14,746 : kivy : GL: Backend used <glew>
2023-02-05 08:34:14,746 : kivy : GL: OpenGL version <b'4.6.0 - Build 31.0.101.2111'>
2023-02-05 08:34:14,746 : kivy : GL: OpenGL vendor <b'Intel'>
2023-02-05 08:34:14,747 : kivy : GL: OpenGL renderer <b'Intel(R) UHD Graphics 630'>
2023-02-05 08:34:14,747 : kivy : GL: OpenGL parsed version: 4, 6
2023-02-05 08:34:14,747 : kivy : GL: Shading version <b'4.60 - Build 31.0.101.2111'>
2023-02-05 08:34:14,747 : kivy : GL: Texture max size <16384>
2023-02-05 08:34:14,747 : kivy : GL: Texture max units <32>
2023-02-05 08:34:14,775 : kivy : Window: auto add sdl2 input provider
2023-02-05 08:34:14,775 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2023-02-05 08:34:14,784 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2023-02-05 08:34:15,081 : AudioInterface : Initialized
2023-02-05 08:34:15,081 : AudioInterface : Loaded SDL 2.0.20
2023-02-05 08:34:15,081 : AudioInterface : Loaded SDL_Mixer 2.0.4
2023-02-05 08:34:15,081 : AudioInterface : Loaded GStreamer 1.18.5.0
2023-02-05 08:34:15,081 : AudioInterface : Loaded GLib 2.62.6
2023-02-05 08:34:15,081 : AudioInterface : Settings requested - rate: 44100, channels: 1, buffer: 2048 samples
2023-02-05 08:34:15,082 : AudioInterface : Settings in use - rate: 44100, channels: 1, buffer: 2048 samples (4096 bytes @ 2 bytes per sample)
2023-02-05 08:34:15,082 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2023-02-05 08:34:15,082 : SoundSystem : Setting master volume to 0.0
2023-02-05 08:34:15,082 : SoundSystem : master_volume in sound_system is deprecated and will be removed in the future.
2023-02-05 08:34:15,082 : AudioInterface : Enabling audio playback
2023-02-05 08:34:15,084 : kivy : Base: Start application main loop
2023-02-05 08:34:15,084 : EventManager : Event: ======'display_lcd_initialized'====== Args={}
2023-02-05 08:34:15,095 : mpfmc : Display: Setting 'lcd' as default display
2023-02-05 08:34:15,100 : EventManager : Event: ======'displays_initialized'====== Args={}
2023-02-05 08:34:15,100 : EventManager : Event: ======'slide_lcd_blank_created'====== Args={}
2023-02-05 08:34:15,100 : EventManager : Event: ======'display_lcd_ready'====== Args={}
2023-02-05 08:34:15,109 : EventManager : Event: ======'init_phase_1'====== Args={}
2023-02-05 08:34:15,111 : EventManager : Event: ======'mc_ready'====== Args={}
2023-02-05 08:34:15,111 : EventManager : Event: ======'init_phase_2'====== Args={}
2023-02-05 08:34:15,113 : ConfigValidator : Your config contains a value for the setting "widgets:text:widgets:text:font_text", but this is not a valid setting name.
2023-02-05 08:34:15,113 : kivy : Base: Leaving application in progress...
2023-02-05 08:34:15,113 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x0000028044E502E0>>, priority=1, kwargs={}, key=UUID('03fa37d5-95e2-493c-8eab-7940c8a6341e'), condition=None, blocking_facility=None) for event init_phase_2. Config File Error in ConfigValidator: Error while loading mode 'base' >> Your config contains a value for the setting "widgets:text:widgets:text:font_text", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
Traceback (most recent call last):
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\core\mode_controller.py", line 74, in _load_modes
    raise e
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\core\mode_controller.py", line 67, in _load_modes
    item.method(config=mode.config.get(item.config_section),
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\slide_player.py", line 269, in validate_config
    self._validate_config_item(slide, slide_settings))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\slide_player.py", line 281, in _validate_config_item
    config['widgets'] = self.machine.widgets.process_config(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_collections\widget.py", line 40, in process_config
    widget_list.append(self.process_widget(widget))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_collections\widget.py", line 81, in process_widget
    self.mc.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 342, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Error while loading mode 'base' >> Your config contains a value for the setting "widgets:text:widgets:text:font_text", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\commands\mc.py", line 225, in __init__
    MpfMc(options=vars(args),
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\app.py", line 955, in run
    runTouchApp()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\base.py", line 379, in idle
    Clock.tick()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\clock.py", line 776, in post_idle
    self._process_events()
  File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\uix\display.py", line 211, in _displays_initialized
    self.mc.displays_initialized()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\core\mc.py", line 349, in displays_initialized
    self._init()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\core\mc.py", line 394, in _init
    self.events.process_event_queue()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 795, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 757, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 706, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x0000028044E502E0>>, priority=1, kwargs={}, key=UUID('03fa37d5-95e2-493c-8eab-7940c8a6341e'), condition=None, blocking_facility=None) for event init_phase_2. Config File Error in ConfigValidator: Error while loading mode 'base' >> Your config contains a value for the setting "widgets:text:widgets:text:font_text", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
2023-02-05 08:34:15,116 : kivy : Stopping child threads... (1 remaining)
2023-02-05 08:34:16,122 : kivy : All child threads stopped.
