2023-02-05 08:33:28,446 : INFO : root : Loading config.
2023-02-05 08:33:28,446 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-02-05 08:33:28,446 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\9014108be8bb19792bb5e6c9e9603b65.mpf_cache
2023-02-05 08:33:28,508 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\0c159a05f39617a30cc1b279562f144f.mpf_cache
2023-02-05 08:33:28,508 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\a4144dd661fe0832b800e50000db3090.mpf_cache
2023-02-05 08:33:28,521 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\0c159a05f39617a30cc1b279562f144f.mpf_cache
2023-02-05 08:33:28,521 : WARNING : ConfigProcessor : Config file in cache changed: C:\pinball\SAW\modes\base\config\base.yaml
2023-02-05 08:33:28,522 : INFO : ConfigProcessor : Loading config from file C:\pinball\SAW\modes\base\config\base.yaml.
2023-02-05 08:33:28,522 : INFO : ConfigProcessor : Loading config: C:\pinball\SAW\modes\base\config\base.yaml
2023-02-05 08:33:28,522 : INFO : ConfigProcessor : Config file cache created: C:\Users\steel\AppData\Local\Temp\c84db42795c08bfb8e4272b3be41e3f4.mpf_cache
2023-02-05 08:33:28,522 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\17aa0c884dad87b4b4047bafdeb78206.mpf_cache
2023-02-05 08:33:28,522 : INFO : ConfigProcessor : Loading config from cache: C:\Users\steel\AppData\Local\Temp\6026628a89ebb09da8c65e4a804bb30f.mpf_cache
2023-02-05 08:33:28,522 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.0-dev33
2023-02-05 08:33:28,522 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2023-02-05-08-33-28-mpf-MSI.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-02-05 08:33:28,522 : INFO : Machine : MPF path: C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf
2023-02-05 08:33:28,522 : INFO : Machine : Machine path: C:\pinball\SAW
2023-02-05 08:33:28,522 : INFO : Machine : Platform: win32
2023-02-05 08:33:28,522 : INFO : Machine : Python executable location: C:\Users\steel\AppData\Local\Programs\Python\Python39\python.exe
2023-02-05 08:33:28,522 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-02-05 08:33:28,522 : INFO : Machine : Initialise MPF.
2023-02-05 08:33:28,694 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.0-dev33', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.0-dev33, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19044-SP0', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19044', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2023-02-05 08:33:28,745 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-02-05 08:33:28,777 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-02-05 08:33:28,777 : INFO : SwitchController : Found active switch: (1002, <Platform.Virtual>) <switch.s_left_flipper>
2023-02-05 08:33:28,777 : INFO : SwitchController : Found active switch: (1003, <Platform.Virtual>) <switch.s_right_flipper>
2023-02-05 08:33:28,777 : INFO : SwitchController : Found active switch: (1000, <Platform.Virtual>) <switch.s_trough1>
2023-02-05 08:33:28,777 : INFO : SwitchController : Found active switch: (1005, <Platform.Virtual>) <switch.s_trough2>
2023-02-05 08:33:28,777 : INFO : SwitchController : Found active switch: (1006, <Platform.Virtual>) <switch.s_trough3>
2023-02-05 08:33:28,777 : ERROR : ConfigValidator : Your config contains a value for the setting "widgets:text:widgets:text:text_font", but this is not a valid setting name.
2023-02-05 08:33:28,777 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 744, in _queue_task_done
    future.result()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialise_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 111, in process_widget
    self.machine.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 342, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_base_started:slides with settings {'widgets': [{'type': 'text', 'text': '(score)', 'number_grouping': True, 'min_digits': 2, 'font_size': 100, '_default_settings': ['type', 'text', 'number_grouping', 'min_digits', 'font_size'], 'x': None, 'y': None, 'anchor_x': 'center', 'anchor_y': 'center', 'round_anchor_x': None, 'round_anchor_y': None, 'opacity': 1.0, 'z': 0, 'reset_animations_events': {}, 'color': [1.0, 1.0, 1.0, 1.0], 'style': [], 'adjust_top': 0, 'adjust_bottom': 0, 'adjust_left': 0, 'adjust_right': 0, 'expire': None, 'key': None, 'widget': None, 'events_when_added': [], 'events_when_removed': [], 'bitmap_font': False, 'font_kerning': True, 'bold': False, 'italic': False, 'halign': 'center', 'valign': 'middle', 'rotation': 0, 'scale': 1.0, 'casing': None, 'animations': None}, {'type': 'text', 'text_font': 'TrajanProRegular', 'text': 'PLAYER (number)', 'y': 10, 'x': 10, 'font_size': 50, 'anchor_x': 'left', 'anchor_y': 'bottom', '_default_settings': ['type', 'text_font', 'text', 'y', 'x', 'font_size', 'anchor_x', 'anchor_y']}, {'type': 'text', 'text': 'BALL (ball)', 'text_font': 'TrajanProRegular', 'y': 10, 'x': 'right-10', 'anchor_x': 'right', 'anchor_y': 'bottom', 'font_size': 50}, {'type': 'text', 'text_font': 'TrajanProRegular', 'text': 'Current Score: (score)', 'y': '40%'}]} >> Your config contains a value for the setting "widgets:text:widgets:text:text_font", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
2023-02-05 08:33:28,794 : INFO : Machine : Starting the main run loop.
2023-02-05 08:33:28,796 : INFO : Machine : Shutting down...
2023-02-05 08:33:28,797 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-02-05 08:33:29,815 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 744, in _queue_task_done
    future.result()
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialise_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 111, in process_widget
    self.machine.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\steel\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\config_validator.py", line 342, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_base_started:slides with settings {'widgets': [{'type': 'text', 'text': '(score)', 'number_grouping': True, 'min_digits': 2, 'font_size': 100, '_default_settings': ['type', 'text', 'number_grouping', 'min_digits', 'font_size'], 'x': None, 'y': None, 'anchor_x': 'center', 'anchor_y': 'center', 'round_anchor_x': None, 'round_anchor_y': None, 'opacity': 1.0, 'z': 0, 'reset_animations_events': {}, 'color': [1.0, 1.0, 1.0, 1.0], 'style': [], 'adjust_top': 0, 'adjust_bottom': 0, 'adjust_left': 0, 'adjust_right': 0, 'expire': None, 'key': None, 'widget': None, 'events_when_added': [], 'events_when_removed': [], 'bitmap_font': False, 'font_kerning': True, 'bold': False, 'italic': False, 'halign': 'center', 'valign': 'middle', 'rotation': 0, 'scale': 1.0, 'casing': None, 'animations': None}, {'type': 'text', 'text_font': 'TrajanProRegular', 'text': 'PLAYER (number)', 'y': 10, 'x': 10, 'font_size': 50, 'anchor_x': 'left', 'anchor_y': 'bottom', '_default_settings': ['type', 'text_font', 'text', 'y', 'x', 'font_size', 'anchor_x', 'anchor_y']}, {'type': 'text', 'text': 'BALL (ball)', 'text_font': 'TrajanProRegular', 'y': 10, 'x': 'right-10', 'anchor_x': 'right', 'anchor_y': 'bottom', 'font_size': 50}, {'type': 'text', 'text_font': 'TrajanProRegular', 'text': 'Current Score: (score)', 'y': '40%'}]} >> Your config contains a value for the setting "widgets:text:widgets:text:text_font", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
2023-02-05 08:33:41,379 : INFO : root : MPF run loop ended.
